# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(editable=False, max_length=255, unique=True)),
                ('content', models.CharField(max_length=255)),
                ('font_color', models.CharField(max_length=255)),
                ('font_weight', models.CharField(max_length=255)),
                ('font_size', models.CharField(max_length=255)),
            ],
        ),
    ]
